spring.application.name=skoob-api

# Profile ativo: se não vier de variável de ambiente, usa "dev"
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configurações comuns a todos os ambientes
spring.jpa.properties.hibernate.format_sql=true